---
- hosts: server
  vars:
    distant_home: "/home/{{ distant_user }}"
    to_bring_back: "{{ distant_home }}/toBringBack"
    vanillapull_dest_path: "{{ distant_home }}/parallel-lab/vanillapull/"
    war_name: "vanillapull-1.0-SNAPSHOT.war"
    tomcat_path: "{{ distant_home }}/apache-tomcat-7.0.52/"
    jetty_path: "{{ distant_home }}/jetty-distribution-9.1.3.v20140225/"
    webappWriterPath: "-DwriterPath={{ to_bring_back }}/threadCount.json"
    full_params: "-Dimplementation=mono -Diterations=500000 -Dusers=1 -Dduration=30 -DnbThreads={{ nbThreads }} -Dserver={{ server }} -Daws={{ aws }} -Dlanguage={{ language }} -DsynchronizationMode=false"
  sudo: yes
  user: ${distant_user}
  tasks:
    - name: clean webapp
      shell: cd {{ vanillapull_dest_path }}; mvn -pl webapp clean package {{ full_params }} {{ webappWriterPath }}
    - name: shutdown tomcat
      shell: ${tomcat_path}/bin/shutdown.sh; pkill -f catalina
      ignore_errors: yes
      sudo: true
    - name: shutdown jetty
      command: bash {{ jetty_path }}/bin/jetty.sh stop
      sudo: true
    - name: shutdown httpcore
      command: wget http://localhost:8080/vanillapull-1.0-SNAPSHOT/stopper/stop/
      ignore_errors: yes
    - name: deploy
      command: ls
      notify: ${server}
  handlers:
    - name: tomcat
      command: ls
      notify: cp init tomcat script
    - name: jetty
      command: ls
      notify: undeploy jetty webapp
    - name: httpcore
      command: ls
      notify: deploy httpcore webapp

    - name: cp init tomcat script
      command: mkdir -p {{ tomcat_path }}/conf/logs/
      sudo: true
      notify: startup tomcat
    - name: startup tomcat
      shell: JAVA_OPTS="{{ full_params }} {{ webappWriterPath }}" nohup {{ tomcat_path }}/bin/startup.sh &
      sudo: true
      notify: undeploy tomcat webapp
    - name: undeploy tomcat webapp
      shell: cd {{ vanillapull_dest_path }}; mvn -pl webapp tomcat7:undeploy  {{ full_params }} {{ webappWriterPath }}
      notify: deploy tomcat webapp
    - name: deploy tomcat webapp
      shell: cd {{ vanillapull_dest_path }}; mvn -pl webapp tomcat7:deploy  {{ full_params }} {{ webappWriterPath }}
    - name: deploy httpcore webapp
      shell: cd {{ vanillapull_dest_path }}; mvn -pl webapp install {{ full_params }} {{ webappWriterPath }}

    - name: undeploy jetty webapp
      shell: rm {{ jetty_path }}/webapps/{{ war_name }}
      ignore_errors: True
      notify: deploy jetty webapp
    - name: deploy jetty webapp
      shell: cp {{ vanillapull_dest_path }}/webapp/target/{{ war_name }} {{ jetty_path }}/webapps/
      sudo: true
      notify: startup jetty
    - name: startup jetty
      command: bash {{ jetty_path }}/bin/jetty.sh start "{{ full_params }} {{ webappWriterPath }}"
      sudo: true