# -*- mode: ruby -*-
# vi: set ft=ruby :

# IP addresses of the gatling and server
@lr_subnet = "192.168.17"
@lr_ip_gatling = "#{@lr_subnet}.2"
@lr_ip_server = "#{@lr_subnet}.3"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use a precise64. You can change that to precise32 if needed
  config.vm.box = "saucy"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"
  
  config.vm.define :gatlingo7 do |config|
    config.vm.host_name = "gatlingo7"
    config.vm.network "private_network", ip: @lr_ip_gatling
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.memory = 1024
      config.vm.network "forwarded_port", guest: 22, host: 12347
    end

    config.vm.provision :shell, :privileged => false, :path => "gatling.sh"
  end
  
  config.vm.define :servero7 do |config|
    config.vm.host_name = "servero7"
    config.vm.network "private_network", ip: @lr_ip_server
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.memory = 1024
      config.vm.network "forwarded_port", guest: 22, host: 23457
      config.vm.network "forwarded_port", guest: 80, host: 8087
      for i in 10001..10010
        config.vm.network :forwarded_port, guest: i, host: i
      end
    end
    
    config.vm.provision :shell, :privileged => false, :path => "server.sh"
  end
end